//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Events.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Events.Domain.Messages-ru", typeof(Messages_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата начала события не может быть позже даты завершения.
        /// </summary>
        internal static string EndAt_Less_StartAt {
            get {
                return ResourceManager.GetString("EndAt_Less_StartAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет доступных мест для этого события.
        /// </summary>
        internal static string NoAvailableSeats {
            get {
                return ResourceManager.GetString("NoAvailableSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не передано количество доступных для бронирования мест .
        /// </summary>
        internal static string Not_Sent_AvailableSeats {
            get {
                return ResourceManager.GetString("Not_Sent_AvailableSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не была передана дата завершения события.
        /// </summary>
        internal static string Not_Sent_EndAt {
            get {
                return ResourceManager.GetString("Not_Sent_EndAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не был передан параметр ID .
        /// </summary>
        internal static string Not_Sent_Id {
            get {
                return ResourceManager.GetString("Not_Sent_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не была передана дата начала события.
        /// </summary>
        internal static string Not_Sent_StartAt {
            get {
                return ResourceManager.GetString("Not_Sent_StartAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не было передано наименование события.
        /// </summary>
        internal static string Not_Sent_Title {
            get {
                return ResourceManager.GetString("Not_Sent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не передано общее количество мест для бронирования.
        /// </summary>
        internal static string Not_Sent_TotalSeats {
            get {
                return ResourceManager.GetString("Not_Sent_TotalSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при отмене бронирования. Предано неверное количество мест.
        /// </summary>
        internal static string RealiseBokingWrongCount {
            get {
                return ResourceManager.GetString("RealiseBokingWrongCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно освободить места события {0}. Событие уже началось.
        /// </summary>
        internal static string TryReleseEventBegun {
            get {
                return ResourceManager.GetString("TryReleseEventBegun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно освободить места события {0}. Событие уже завершилось.
        /// </summary>
        internal static string TryReleseEventCompleted {
            get {
                return ResourceManager.GetString("TryReleseEventCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бронирование мест недоступно. Событие {0} уже началось.
        /// </summary>
        internal static string TryReserveEventBegun {
            get {
                return ResourceManager.GetString("TryReserveEventBegun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бронирование мест недоступно. Событие {0} уже закончилось.
        /// </summary>
        internal static string TryReserveEventCompleted {
            get {
                return ResourceManager.GetString("TryReserveEventCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество доступных мест должно быть больше или равно нулю и не превышать общее количество мест.
        /// </summary>
        internal static string WrongEventAvailableSeats {
            get {
                return ResourceManager.GetString("WrongEventAvailableSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общее количество мест должно быть больше нуля.
        /// </summary>
        internal static string WrongEventTotalSeats {
            get {
                return ResourceManager.GetString("WrongEventTotalSeats", resourceCulture);
            }
        }
    }
}
