//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BestEvents.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BestEvents.Domain.Messages-ru", typeof(Messages_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бронирование отклонено, так как событие  уже завершилось.
        /// </summary>
        internal static string BookingRejectedEventCompleted {
            get {
                return ResourceManager.GetString("BookingRejectedEventCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бронирование уже обработано.
        /// </summary>
        internal static string DoubleBookingProcessing {
            get {
                return ResourceManager.GetString("DoubleBookingProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата начала события не может быть позже даты завершения.
        /// </summary>
        internal static string EndAt_Less_StartAt {
            get {
                return ResourceManager.GetString("EndAt_Less_StartAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не передано количество доступных для бронирования мест .
        /// </summary>
        internal static string No_AvailableSeats {
            get {
                return ResourceManager.GetString("No_AvailableSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не была передана дата завершения события.
        /// </summary>
        internal static string No_EndAt {
            get {
                return ResourceManager.GetString("No_EndAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не был передан параметр ID .
        /// </summary>
        internal static string No_Id {
            get {
                return ResourceManager.GetString("No_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не была передана дата начала события.
        /// </summary>
        internal static string No_StartAt {
            get {
                return ResourceManager.GetString("No_StartAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не было передано наименование события.
        /// </summary>
        internal static string No_Title {
            get {
                return ResourceManager.GetString("No_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не передано общее количество мест для бронирования.
        /// </summary>
        internal static string No_TotalSeats {
            get {
                return ResourceManager.GetString("No_TotalSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет доступных мест для этого события.
        /// </summary>
        internal static string NoAvailableSeats {
            get {
                return ResourceManager.GetString("NoAvailableSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет прав на отмену бронирования.
        /// </summary>
        internal static string NoRightOfCancelBooking {
            get {
                return ResourceManager.GetString("NoRightOfCancelBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при отмене бронирования. Предано неверное количество мест.
        /// </summary>
        internal static string RealiseBokingWrongCount {
            get {
                return ResourceManager.GetString("RealiseBokingWrongCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не задан логин.
        /// </summary>
        internal static string UserNameIsEmpty {
            get {
                return ResourceManager.GetString("UserNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество доступных мест должно быть больше или равно нулю и не превышать общее количество мест.
        /// </summary>
        internal static string WrongEventAvailableSeats {
            get {
                return ResourceManager.GetString("WrongEventAvailableSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общее количество мест должно быть больше нуля.
        /// </summary>
        internal static string WrongEventTotalSeats {
            get {
                return ResourceManager.GetString("WrongEventTotalSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роль {0} не подддерживается сервисом.
        /// </summary>
        internal static string WrongRole {
            get {
                return ResourceManager.GetString("WrongRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный формат идентификатора пользователя.
        /// </summary>
        internal static string WrongUserId {
            get {
                return ResourceManager.GetString("WrongUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин должен содержать только латинские символы.
        /// </summary>
        internal static string WrongUserNameFormat {
            get {
                return ResourceManager.GetString("WrongUserNameFormat", resourceCulture);
            }
        }
    }
}
