//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookings.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bookings.Domain.Messages-ru", typeof(Messages_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бронирование уже было отменено ранее.
        /// </summary>
        internal static string AttemptToCancelCancelledBooking {
            get {
                return ResourceManager.GetString("AttemptToCancelCancelledBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бронирование ранее было отклонено.
        /// </summary>
        internal static string AttemptToCancelRejectedBooking {
            get {
                return ResourceManager.GetString("AttemptToCancelRejectedBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бронирование отклонено, так как событие  уже завершилось.
        /// </summary>
        internal static string BookingRejectedEventCompleted {
            get {
                return ResourceManager.GetString("BookingRejectedEventCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бронирование уже было отменено ранее.
        /// </summary>
        internal static string DoubleBookingCancel {
            get {
                return ResourceManager.GetString("DoubleBookingCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бронирование уже обработано.
        /// </summary>
        internal static string DoubleBookingProcessing {
            get {
                return ResourceManager.GetString("DoubleBookingProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустое имя пользователя.
        /// </summary>
        internal static string EmptyUserName {
            get {
                return ResourceManager.GetString("EmptyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет доступных мест для этого события.
        /// </summary>
        internal static string NoAvailableSeats {
            get {
                return ResourceManager.GetString("NoAvailableSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет прав на отмену бронирования.
        /// </summary>
        internal static string NoRightOfCancelBooking {
            get {
                return ResourceManager.GetString("NoRightOfCancelBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь {0} не найден.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для пользователя  id = {0} не определена роль.
        /// </summary>
        internal static string WrongRole {
            get {
                return ResourceManager.GetString("WrongRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный формат идентификатора пользователя (id = {0}).
        /// </summary>
        internal static string WrongUserId {
            get {
                return ResourceManager.GetString("WrongUserId", resourceCulture);
            }
        }
    }
}
