version: '3.8'

services:
  events-db:
    image: postgres:16-alpine
    container_name: bestevents-events-db
    ports:
       - "5433:5432"
    environment:
      POSTGRES_DB: events
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - events-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d events"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  events-db-data:
    