version: '3.8'

services:
  bookings-db:
    image: postgres:16-alpine
    container_name: bestevents-bookings-db
    ports:
       - "5433:5432"
    environment:
      POSTGRES_DB: bookings
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - bookings-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bookings"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  bookings-db-data:
    