//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BestEvents {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BestEvents.Messages-ru", typeof(Messages_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бронирование с идентификатором {0} не найдено.
        /// </summary>
        public static string BookingNotFound {
            get {
                return ResourceManager.GetString("BookingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бронирование не найдено.
        /// </summary>
        public static string BookingNotFoundShort {
            get {
                return ResourceManager.GetString("BookingNotFoundShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бронирование с идентификатором {0} не найдено. Обновление не произведено.
        /// </summary>
        public static string BookingNotReplaced {
            get {
                return ResourceManager.GetString("BookingNotReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при обработке бронирования {0}: {1}.
        /// </summary>
        public static string BookingProcessingError {
            get {
                return ResourceManager.GetString("BookingProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бронирование {0} отклонено, так как событие {1} уже завершилось.
        /// </summary>
        public static string BookingRejectedEventCompleted {
            get {
                return ResourceManager.GetString("BookingRejectedEventCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бронирование {0} отклонено, так как событие {1} не существует или оно было удалено.
        /// </summary>
        public static string BookingRejectedEventNoExist {
            get {
                return ResourceManager.GetString("BookingRejectedEventNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При создании брони не передан идентификатор события.
        /// </summary>
        public static string CreateBooking_No_EventId {
            get {
                return ResourceManager.GetString("CreateBooking_No_EventId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бронирование не создано.
        /// </summary>
        public static string CreateBookingError {
            get {
                return ResourceManager.GetString("CreateBookingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бронирование не создано, так как события с идентификатором {0} уже завершилось.
        /// </summary>
        public static string CreateBookingEventCompleted {
            get {
                return ResourceManager.GetString("CreateBookingEventCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бронирование не создано, так как события с идентификатором {0} не существует.
        /// </summary>
        public static string CreateBookingEventNotFound {
            get {
                return ResourceManager.GetString("CreateBookingEventNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попытка подтверждения брони {0}, которая уже подтверждена.
        /// </summary>
        public static string DoubleBookingConfirm {
            get {
                return ResourceManager.GetString("DoubleBookingConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попытка отклонения брони {0}, которая уже отклонена.
        /// </summary>
        public static string DoubleBookingReject {
            get {
                return ResourceManager.GetString("DoubleBookingReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата начала события не может быть позже даты завершения.
        /// </summary>
        public static string EndAt_Less_StartAt {
            get {
                return ResourceManager.GetString("EndAt_Less_StartAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Событие с идентификатором {0} не найдено. Удаление не произведено.
        /// </summary>
        public static string EventNotDeleted {
            get {
                return ResourceManager.GetString("EventNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Событие с идентификатором {0} не найдено.
        /// </summary>
        public static string EventNotFound {
            get {
                return ResourceManager.GetString("EventNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Событие не найдено.
        /// </summary>
        public static string EventNotFoundShort {
            get {
                return ResourceManager.GetString("EventNotFoundShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Событие с идентификатором {0} не найдено. Обновление не произведено.
        /// </summary>
        public static string EventNotReplaced {
            get {
                return ResourceManager.GetString("EventNotReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметр id в строке запроса {0} не совпадает с параметром id в теле запроса {1}.
        /// </summary>
        public static string MismatchIdInReplaceRequest {
            get {
                return ResourceManager.GetString("MismatchIdInReplaceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не передано количество доступных для бронирования мест .
        /// </summary>
        public static string No_AvailableSeats {
            get {
                return ResourceManager.GetString("No_AvailableSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не была передана дата завершения события.
        /// </summary>
        public static string No_EndAt {
            get {
                return ResourceManager.GetString("No_EndAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не был передан параметр ID .
        /// </summary>
        public static string No_Id {
            get {
                return ResourceManager.GetString("No_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не была передана дата начала события.
        /// </summary>
        public static string No_StartAt {
            get {
                return ResourceManager.GetString("No_StartAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не было передано наименование события.
        /// </summary>
        public static string No_Title {
            get {
                return ResourceManager.GetString("No_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не передано общее количество мест для бронирования.
        /// </summary>
        public static string No_TotalSeats {
            get {
                return ResourceManager.GetString("No_TotalSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет доступных мест для этого события.
        /// </summary>
        public static string NoAvailableSeats {
            get {
                return ResourceManager.GetString("NoAvailableSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при отмене бронирования. Предано неверное количество мест.
        /// </summary>
        public static string RealiseBokingWrongCount {
            get {
                return ResourceManager.GetString("RealiseBokingWrongCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недопустимые параметры в запросе.
        /// </summary>
        public static string RequestWrongParameters {
            get {
                return ResourceManager.GetString("RequestWrongParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попытка подтверждения уже отклоненной брони {0}.
        /// </summary>
        public static string TryConfirmRejectedBooking {
            get {
                return ResourceManager.GetString("TryConfirmRejectedBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторная отклонения уже подтвержденной брони {0}.
        /// </summary>
        public static string TryRedjectConfirmedBooking {
            get {
                return ResourceManager.GetString("TryRedjectConfirmedBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестный тип ошибки.
        /// </summary>
        public static string UndefinedError {
            get {
                return ResourceManager.GetString("UndefinedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Непредвиденная ошибка при работе сервиса бронирования.
        /// </summary>
        public static string UnexpectedBookingError {
            get {
                return ResourceManager.GetString("UnexpectedBookingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный формат даты завершения события.
        /// </summary>
        public static string WronFormat_EndAt {
            get {
                return ResourceManager.GetString("WronFormat_EndAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный формат даты начала события.
        /// </summary>
        public static string WronFormat_StartAt {
            get {
                return ResourceManager.GetString("WronFormat_StartAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Строка Id не соответствует формату GUID.
        /// </summary>
        public static string Wrong_Id_Format {
            get {
                return ResourceManager.GetString("Wrong_Id_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество доступных мест должно быть больше или равно нулю и не превышать общее количество мест.
        /// </summary>
        public static string WrongEventAvailableSeats {
            get {
                return ResourceManager.GetString("WrongEventAvailableSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общее количество мест должно быть больше нуля.
        /// </summary>
        public static string WrongEventTotalSeats {
            get {
                return ResourceManager.GetString("WrongEventTotalSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попытка пагинации с недопустимым значением номера страницы (page={0}).
        /// </summary>
        public static string WrongPageForPagination {
            get {
                return ResourceManager.GetString("WrongPageForPagination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попытка пагинации с недопустимым значением размера выборки на странице (size={0}).
        /// </summary>
        public static string WrongSizeForPagination {
            get {
                return ResourceManager.GetString("WrongSizeForPagination", resourceCulture);
            }
        }
    }
}
