{
 "title": "BestEvents",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Latency p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket[$__rate_interval])) by (le, job))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(http_server_active_requests) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket[$__rate_interval])) by (le, job))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count[1m])) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency p50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_request_duration_seconds_bucket[$__rate_interval])) by (le, job))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}