services:
  users.presentation:
    image: ${DOCKER_REGISTRY-}userspresentation
    build:
      context: .
      dockerfile: Users/Users.Presentation/Dockerfile
    environment:
      - ConnectionStrings__Default=Host=db-users;Port=5432;Database=users;Username=postgres;Password=postgres;
      - Kafka__BootstrapServers=kafka:29092
      - JwtSettings__SecretKey=${JWT_SECRET_KEY}
      - Otlp__Endpoint=http://jaeger:4317
    ports:
      - "5001:8080"
    depends_on:
      kafka:
        condition: service_started
      db-users:
        condition: service_healthy

  events.presentation:
    image: ${DOCKER_REGISTRY-}eventspresentation
    build:
      context: .
      dockerfile: Events/Events.Presentation/Dockerfile
    environment:
      - ConnectionStrings__Default=Host=db-events;Port=5432;Database=events;Username=postgres;Password=postgres;
      - Kafka__BootstrapServers=kafka:29092
      - JwtSettings__SecretKey=${JWT_SECRET_KEY}
      - RedisSettings__Password=${REDIS_PASSWORD}
      - RedisSettings__Endpoints=events-redis:6379   
      - Otlp__Endpoint=http://jaeger:4317
    ports:
      - "5002:8080"
    depends_on:
      kafka:
        condition: service_started
      db-events:
        condition: service_healthy
      redis:
        condition: service_healthy

  bookings.presentation:
    image: ${DOCKER_REGISTRY-}bookingspresentation
    build:
      context: .
      dockerfile: Bookings/Bookings.Presentation/Dockerfile
    environment:
      - ConnectionStrings__Default=Host=db-bookings;Port=5432;Database=bookings;Username=postgres;Password=postgres;
      - Kafka__BootstrapServers=kafka:29092
      - JwtSettings__SecretKey=${JWT_SECRET_KEY}
      - Otlp__Endpoint=http://jaeger:4317
    ports:
      - "5003:8080"
    depends_on:
      kafka:
        condition: service_started
      db-bookings:
        condition: service_healthy
        

  db-users:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      Otlp__Endpoint: http://jaeger:4317
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d users"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  db-events:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: events
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      Otlp__Endpoint: http://jaeger:4317
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d events"] 
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  db-bookings:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: bookings 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      Otlp__Endpoint: http://jaeger:4317
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bookings"] 
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://127.0.0.1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

  redis:
    image: redis:7.2-alpine
    container_name: events-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: eventapi-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  jaeger:
    image: jaegertracing/all-in-one:1.56
    container_name: eventapi-jaeger
    ports:
      - "16686:16686"   
      - "4317:4317"    
    environment:
      COLLECTOR_OTLP_ENABLED: "true"

  grafana:
    image: grafana/grafana:10.4.2
    container_name: eventapi-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana
volumes:
  grafana-data: