//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Events.Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Events.Application.Messages-ru", typeof(Messages_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось освободить место на событие {0}, зарезервированное для бронирования {1}..
        /// </summary>
        public static string ErrorReleaseSeats {
            get {
                return ResourceManager.GetString("ErrorReleaseSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось зарезервировать место на событие {0} для бронирования {1}..
        /// </summary>
        public static string ErrorReserveSeats {
            get {
                return ResourceManager.GetString("ErrorReserveSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметр id в строке запроса {0} не совпадает с параметром id в теле запроса {1}.
        /// </summary>
        public static string MismatchIdInReplaceRequest {
            get {
                return ResourceManager.GetString("MismatchIdInReplaceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Освобождено место на событие {0}, зарезервированное для бронирования {1}.
        /// </summary>
        public static string SeatsReleased {
            get {
                return ResourceManager.GetString("SeatsReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарезервировано место на событие {0} для бронирования {1}.
        /// </summary>
        public static string SeatsReserved {
            get {
                return ResourceManager.GetString("SeatsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попытка пагинации с недопустимым значением номера страницы (page={0}).
        /// </summary>
        public static string WrongPageForPagination {
            get {
                return ResourceManager.GetString("WrongPageForPagination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попытка пагинации с недопустимым значением размера выборки на странице (size={0}).
        /// </summary>
        public static string WrongSizeForPagination {
            get {
                return ResourceManager.GetString("WrongSizeForPagination", resourceCulture);
            }
        }
    }
}
